on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - main
    types:
      - opened
 
jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: streetsidesoftware/cspell-action@v6
        with:
          files: |
            docs/skos/*.{json,rdf,ttl}
            !docs/skos/amagi_ebu_IdentifierTypeCS.ttl  # Exclude specific file
            !docs/skos/amagi_ebu_IdentifierTypeCS.rdf  # Exclude specific file
            !docs/skos/amagi_ebu_IdentifierTypeCS_amgext.rdf  # Exclude specific file
          incremental_files_only: false
          config: './.vscode/cspell.json'
