on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches:
      - main
    types:
      - opened
 
jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: streetsidesoftware/cspell-action@v3
        with:
          files: |
            docs/skos/*.{json,rdf,ttl}
          incremental_files_only: false
          config: './.vscode/cspell.json'
